// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG8jLi4D-sBCDLCObQcrecfeWVDP3ipcA',
    appId: '1:104809315386:web:9d82982b3b22ba67108903',
    messagingSenderId: '104809315386',
    projectId: 'edspertid',
    authDomain: 'edspertid.firebaseapp.com',
    storageBucket: 'edspertid.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyAV2NvXZHYzuU95cA5wJkS6PMwGAjQMs',
    appId: '1:104809315386:android:e5acf8f517e05a1f108903',
    messagingSenderId: '104809315386',
    projectId: 'edspertid',
    storageBucket: 'edspertid.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdDaN2Y9QCSAI4EqjuUh7t_cLZKfkGiao',
    appId: '1:104809315386:ios:6d9e2c081703a0d9108903',
    messagingSenderId: '104809315386',
    projectId: 'edspertid',
    storageBucket: 'edspertid.appspot.com',
    iosClientId: '104809315386-svpf5mg1uq3eglph3i5oi2g0vfm3uj6i.apps.googleusercontent.com',
    iosBundleId: 'com.muhammadhamdani.edspertid.edspertid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdDaN2Y9QCSAI4EqjuUh7t_cLZKfkGiao',
    appId: '1:104809315386:ios:a3aa865be8cd4ba7108903',
    messagingSenderId: '104809315386',
    projectId: 'edspertid',
    storageBucket: 'edspertid.appspot.com',
    iosClientId: '104809315386-59sc420ipv14vhlr1nacv2e40ss93ncg.apps.googleusercontent.com',
    iosBundleId: 'com.muhammadhamdani.edspertid.edspertid.RunnerTests',
  );
}
